version: "3.7"
services:
  app:
    build:
      args:
        user: tomasz
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: bylec-chess
    container_name: bylec-chess-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - bylec-chess

  db:
    image: mysql:5.7
    container_name: bylec-chess-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/var/lib/mysql
    networks:
      - bylec-chess

  nginx:
    image: nginx:alpine
    container_name: bylec-chess-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - bylec-chess

networks:
  bylec-chess:
    driver: bridge
